spring.config.import=optional:file:.env[.properties]
spring.application.name=sistema-restaurante-backend
# Variables ocultas
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
server.servlet.context-path=/api
server.port=${SERVER_PORT:8080}

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

#Mercado Pago
mercadopago.access-token=APP_USR-7070486388275174-061721-92037e349e38998806319643976c107d-3482398972