spring.application.name=sistema-restaurante-backend
spring.config.import=optional:dotenv:

# Variables ocultas
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
server.servlet.context-path=/api
server.port=${SERVER_PORT:8080}

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect